// Generated by CoffeeScript 1.9.2
var Group, express, render404, router;

express = require('express');

router = express.Router();

Group = require('../models/Group.js');

render404 = function(res) {
  res.render('404', {
    givenTitle: 'BetLog'
  });
};

router.get('/', function(req, res) {
  res.render('home', {
    givenTitle: 'Bet Log'
  });
});

router.get('/group/', function(req, res) {
  return render404(res);
});

router.get('/event/', function(req, res) {
  return render404(res);
});

router.get('/group/:groupName', function(req, res) {
  var groupName;
  groupName = req.params.groupName;
  Group.findGroup(groupName, function(err, result) {
    if (err) {
      throw err;
    }
    if (result === 'found') {
      Group.findGroupEvents(groupName, function(err, events, options) {
        res.render('groupfound', {
          givenTitle: groupName,
          events: events,
          options: options
        });
      });
    } else {
      render404(res);
    }
  });
});

router.get('/event/:eventId', function(req, res) {
  var eventId;
  eventId = req.params.eventId;
  Group.findEvent(eventId, function(err, eventy, options, bets) {
    if (eventy === void 0) {
      render404(res);
    } else {
      res.render('event', {
        givenTitle: eventy.eventName,
        event: eventy,
        options: options,
        bets: bets
      });
    }
  });
});

router.get('/creategrouppage', function(req, res) {
  res.render('creategroup', {
    givenTitle: 'Bet Log'
  });
});

router.get('/creategroupnametaken', function(req, res) {
  res.render('groupnametaken', {
    givenTitle: 'Bet Log'
  });
});

router.get('/groupnotfound', function(req, res) {
  res.render('groupnotfound', {
    givenTitle: 'Bet Log'
  });
});

router.get('/joingrouppage', function(req, res) {
  res.render('joingroup', {
    givenTitle: 'Bet Log'
  });
});

router.get('/homeinstructions', function(req, res) {
  res.render('homeinstructions', {
    givenTitle: 'Bet Log'
  });
});

router.post('/creategrouppage', function(req, res) {
  res.render('creategroup', {
    givenTitle: 'Bet Log'
  });
});

router.post('/joingrouppage', function(req, res) {
  res.render('joingroup', {
    givenTitle: 'Bet Log'
  });
});

router.post('/creategroup', function(req, res) {
  var groupName;
  groupName = req.body.groupName;
  Group.addGroup(groupName, function(err, group) {
    if (err) {
      throw err;
    }
    if (group === 'found') {
      res.redirect('/creategroupnametaken');
    } else {
      res.redirect('/group/' + groupName);
    }
  });
});

router.post('/joingroup', function(req, res) {
  var groupName;
  groupName = req.body.groupName;
  Group.findGroup(groupName, function(err, result) {
    if (result === 'notfound') {
      res.redirect('/groupnotfound');
    } else if (result === 'found') {
      res.redirect('/group/' + groupName);
    }
  });
});

router.post('/createeventpage', function(req, res) {
  var groupName;
  groupName = req.body.groupName;
  res.render('createevent', {
    givenTitle: 'Create Event',
    groupName: groupName
  });
});

router.post('/createevent', function(req, res) {
  var eventCreator, eventName, eventPassword, groupName, options;
  options = [];
  groupName = req.body.groupName;
  eventName = req.body.eventName;
  eventCreator = req.body.eventCreator;
  eventPassword = req.body.eventPassword;
  options[0] = req.body.option1;
  options[1] = req.body.option2;
  Group.addEvent(groupName, eventName, eventPassword, eventCreator, options, function(err, eventId) {
    if (err) {
      throw err;
    }
    res.redirect('/event/' + eventId);
  });
});

router.post('/createbetpage', function(req, res) {
  var eventId, groupName, optionId, optionName;
  optionId = req.body.optionId;
  eventId = req.body.eventId;
  groupName = req.body.groupName;
  optionName = req.body.optionName;
  res.render('createbet', {
    givenTitle: 'Place Bet',
    groupName: groupName,
    optionId: optionId,
    optionName: optionName,
    eventId: eventId
  });
});

router.post('/createbet', function(req, res) {
  var adr, amt, betterAddress, betterAmount, betterName, carrier, eventId, optionId, optionName;
  eventId = req.body.eventId;
  optionId = req.body.optionId;
  optionName = req.body.optionName;
  betterName = req.body.betterName;
  betterAmount = req.body.betterAmount;
  betterAddress = req.body.betterAddress;
  carrier = req.body.carrier;
  adr = void 0;
  amt = void 0;
  if (betterAmount[0] !== '$' && (betterAmount[0] === '0' || betterAmount[0] === '1' || betterAmount[0] === '2' || betterAmount[0] === '3' || betterAmount[0] === '4' || betterAmount[0] === '5' || betterAmount[0] === '6' || betterAmount[0] === '7' || betterAmount[0] === '8' || betterAmount[0] === '9')) {
    amt = '$' + betterAmount;
  } else {
    amt = betterAmount;
  }
  if (betterAddress.length < 10 || parseInt(betterAddress) === NaN) {
    adr = null;
  } else if (carrier === 'AT&T') {
    adr = betterAddress + '@txt.att.net';
  } else if (carrier === 'Sprint') {
    adr = betterAddress + '@messaging.sprintpcs.com';
  } else if (carrier === 'T-Mobile') {
    adr = betterAddress + '@tmomail.net';
  } else if (carrier === 'Verizon') {
    adr = betterAddress + '@vtext.com';
  } else if (carrier === 'Virgin Mobile') {
    adr = betterAddress + '@vmobl.com';
  } else {
    adr = null;
  }
  Group.addBet(eventId, optionId, optionName, betterName, amt, adr, function(err) {
    if (err) {
      throw err;
    }
    res.redirect('/event/' + eventId);
  });
});

router.post('/selectwinpage', function(req, res) {
  var eventCreator, eventId, eventName, groupName, opt1id, opt1name, opt2id, opt2name;
  eventId = req.body.eventId;
  eventName = req.body.eventName;
  eventCreator = req.body.eventCreator;
  groupName = req.body.groupName;
  opt1id = req.body.opt1id;
  opt2id = req.body.opt2id;
  opt1name = req.body.opt1name;
  opt2name = req.body.opt2name;
  res.render('selectwinpage', {
    givenTitle: eventName,
    groupName: groupName,
    eventCreator: eventCreator,
    eventName: eventName,
    eventId: eventId,
    opt1id: opt1id,
    opt2id: opt2id,
    opt1name: opt1name,
    opt2name: opt2name
  });
});

router.post('/eventPass', function(req, res) {
  var eventCreator, eventId, eventName, eventPassword, groupName, opt1id, opt1name, opt2id, opt2name;
  eventId = req.body.eventId;
  eventName = req.body.eventName;
  eventCreator = req.body.eventCreator;
  groupName = req.body.groupName;
  opt1id = req.body.opt1id;
  opt2id = req.body.opt2id;
  opt1name = req.body.opt1name;
  opt2name = req.body.opt2name;
  eventPassword = req.body.eventPassword;
  Group.checkPassword(eventId, eventPassword, function(err, bool) {
    if (err) {
      throw err;
    }
    if (bool) {
      res.render('selectwinner', {
        givenTitle: eventName,
        groupName: groupName,
        eventCreator: eventCreator,
        eventName: eventName,
        eventId: eventId,
        opt1id: opt1id,
        opt2id: opt2id,
        opt1name: opt1name,
        opt2name: opt2name
      });
    } else {
      res.render('selectwinpage', {
        givenTitle: eventName,
        groupName: groupName,
        eventCreator: eventCreator,
        eventName: eventName,
        eventId: eventId,
        opt1id: opt1id,
        opt2id: opt2id,
        opt1name: opt1name,
        opt2name: opt2name
      });
    }
  });
});

router.post('/selectwin', function(req, res) {
  var eventId, groupName, loseOptId, winOptId;
  groupName = req.body.groupName;
  eventId = req.body.eventId;
  winOptId = req.body.winOptId;
  loseOptId = req.body.loseOptId;
  Group.declareWin(eventId, winOptId, loseOptId, function(err) {
    if (err) {
      throw err;
    }
    res.redirect('/event/' + eventId);
  });
});

router.post('/createbetmatchpage', function(req, res) {
  var betId, betterAddress, betterAmount, betterName, eventId, groupName, option2Id, option2Name, optionId, optionName;
  eventId = req.body.eventId;
  optionId = req.body.optionId;
  option2Id = req.body.option2Id;
  option2Name = req.body.option2Name;
  optionName = req.body.optionName;
  betId = req.body.betId;
  betterName = req.body.name;
  betterAmount = req.body.amount;
  betterAddress = req.body.address;
  groupName = req.body.groupName;
  res.render('matchbet', {
    givenTitle: 'Match Bet',
    groupName: groupName,
    eventId: eventId,
    matchName: betterName,
    optionId: optionId,
    optionName: optionName,
    betterName: betterName,
    betterAmount: betterAmount,
    betterAddress: betterAddress,
    option2Name: option2Name,
    option2Id: option2Id,
    matchId: betId
  });
});

router.post('/createbetmatch', function(req, res) {
  var adr, betterAddress, betterAmount, betterName, carrier, eventId, matchId, matchName, optionId, optionName;
  eventId = req.body.eventId;
  optionId = req.body.optionId;
  matchId = req.body.matchId;
  matchName = req.body.matchName;
  optionName = req.body.optionName;
  betterName = req.body.betterName;
  betterAmount = req.body.betterAmount;
  betterAddress = req.body.betterAddress;
  carrier = req.body.carrier;
  adr = void 0;
  if (carrier === 'AT&T') {
    adr = betterAddress + '@txt.att.net';
  } else if (carrier === 'Sprint') {
    adr = betterAddress + '@messaging.sprintpcs.com';
  } else if (carrier === 'T-Mobile') {
    adr = betterAddress + '@tmomail.net';
  } else if (carrier === 'Verizon') {
    adr = betterAddress + '@vtext.com';
  } else if (carrier === 'Virgin Mobile') {
    adr = betterAddress + '@vmobl.com';
  } else {
    adr = null;
  }
  Group.addBetMatch(eventId, optionId, matchId, matchName, optionName, betterName, betterAmount, adr, function(err) {
    if (err) {
      throw err;
    }
    res.redirect('/event/' + eventId);
  });
});

module.exports = router;
